### ISSUE TITLE
Link to summon provider documentation inside repo is dead.

### ISSUE THREAD

**Issue by vroad** [gopasspw/gopass#1762]
### Summary
Link to summon provider documentation inside repo is dead.
The same doc is available in another repo, so you just forgot to remove from README?

https://github.com/gopasspw/gopass#further-documentation
https://github.com/gopasspw/gopass-summon-provider

**Comment by dominikschulz** [comment]
Thank you for reporting this issue.

I believe this was fixed already. If not freel free to re-open.

**Comment by vroad** [comment]
No it's not fixed yet. I said that "Gopass as Summon provider" in "Further Documentation" section should be removed. We already have a link to the provider in "integrations" section: 

https://github.com/gopasspw/gopass/blob/v1.12.0/README.md#integrationshttps://github.com/gopasspw/gopass#integrations

**Comment by dominikschulz** [comment]
I'm sorry, your links seen broken and I don't understand what you're trying to say.

Just send a PR to fix it, please.
Thank you!

**Comment by vroad** [comment]
Somehow the link is repeated twice.

It's just matter of removing dead link, I'll try creating a PR later on, thanks.
