### ISSUE TITLE
busybox vi wont edit files -- vi -i unrecognized option

### ISSUE THREAD

**Issue by chereskata** [gopasspw/gopass#2435]
### Summary
Trying to edit a secret with export EDITOR=vi in Alpine Linux does lead to an error message

### Steps To Reproduce

1. Install busybox and symlink vi to busybox binary or use a busybox based distro in a vm
2. run `gopass edit Test`

### Expected behavior
Open vi to edit some data

### Environment
- OS: Alpine Linux edge
- OS version: 5.15.80-0-lts x86_64 Linux
- gopass Version: gopass 1.14.9 go1.19.3 linux amd64
- Installation method: pkgs.alpinelinux.org (apk package manager)

### Console output
```
gopass> edit Test
[ 0] passwordstore/test
[ 1] passwordstore/test2

Found secrets - Please select an entry (q to abort) [0]: Entry Test not found. Creating new secret ...
vi: unrecognized option: i
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: vi [-c CMD] [-R] [-H] [FILE]...

Edit FILE

	-c CMD	Initial command to run ($EXINIT and ~/.exrc also available)
	-R	Read-only
	-H	List available features
 failed to invoke editor: failed to run vi with /dev/shm/gopass-edit1583341854/secret file: exit status 1
 user aborted
```

**Comment by dominikschulz** [comment]
Should have been fixed with https://github.com/gopasspw/gopass/pull/2427.

Could you try again with that build?

**Comment by chereskata** [comment]
@dominikschulz Thanks for the fast reply. I will report back when gopass gets updated in alpine

**Comment by dominikschulz** [comment]
Should have been fixed in 1.15.0. Otherwise reopen, please.

**Comment by chereskata** [comment]
Thank you,

i will test it, once it is available in alpine repos.

Best wishes

**Comment by chereskata** [comment]
Hello @dominikschulz,

as of 15.0 the problem still occours.

```sh
gopass> edit test
...
Found secrets - Please select an entry (q to abort) [0]: q
⚠ Entry test not found. Creating new secret ...
vi: unrecognized option: i
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: vi [-c CMD] [-R] [-H] [FILE]...

Edit FILE

	-c CMD	Initial command to run ($EXINIT and ~/.exrc also available)
	-R	Read-only
	-H	List available features
❌ failed to invoke editor: failed to run vi with /dev/shm/gopass-edit3988897509/secret file: exit status 1
gopass> version
gopass 1.15.0 go1.19.4 linux amd64
<root>     - gpg 2.2.40 - gitfs 2.38.1
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fossilfs, fs, gitfs
```

Thanks a lot

**Comment by dominikschulz** [comment]
So when run `gopass edit test` with `EDITOR=/usr/local/bin/vi` and `/usr/local/bin/vi` being a hardlink to the busybox binary it works.

I see this line in my debug.log:

```
editor.vimOptions	Editor vi is not known to be vim compatible
```

I will add some more logging, but right now I can't reproduce this.
You might run `gopass edit test` with `GOPASS_DEBUG_LOG=/some/file.log` check that around `vimOptions`.

**Comment by dominikschulz** [comment]
Sorry, there was at least one case not covered in 1.15.0. Should be fixed in 1.15.1.

**Comment by chereskata** [comment]
Thanks for the work :)
