### ISSUE TITLE
Path is ignored while initializing gopass root

### ISSUE THREAD

**Issue by frntn** [gopasspw/gopass#876]
### Summary

`gopass init` doesn't allow alternate root path

### Steps To Reproduce
```
[~] 
>_ gopass init --path $HOME/foobar
[init] Initializing a new password store ...
Please select a private key for encrypting secrets:
[0] gpg - 0xD385289FA809234F - Matthieu Fronton <m@tthieu.fr>
Please enter the number of a key (0-0, [q]uit) [0]: 
[init] Initializing git repository (gitcli) ...
Use Matthieu Fronton (m@tthieu.fr) for password store git config? [Y/n/q]: 
[init] Git initialized
[init] Password store /home/frntn/foobar initialized for:
[init]   0xD385289FA809234F - Matthieu Fronton <m@tthieu.fr>

[~] 
>_ gopass
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: ^C
```
And we can see the incorrectly generated config file `$HOME/.config/gopass/config.yml ` : 
```yaml
root:
  askformore: false
  autoclip: true
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: true
  path: gpgcli-gitcli-fs+file:///home/frntn/.password-store
  recipient_hash:
    .gpg-id: 3078443338353238394641383039323334460aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
  safecontent: false
  usesymbols: false
mounts: {}
version: 1.8.1-git+HEAD
```

### Expected behavior
The generated file should look like this : 
```yaml
root:
  askformore: false
  autoclip: true
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: true
  path: gpgcli-gitcli-fs+file:///home/frntn/foobar
  recipient_hash:
    .gpg-id: 3078443338353238394641383039323334460aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
  safecontent: false
  usesymbols: false
mounts: {}
version: 1.8.1-git+HEAD

```

### Environment

- OS: `Ubuntu 18.04`
- OS version: `4.15.0-23-generic x86_64 GNU/Linux`
- gopass Version: `gopass 1.8.1-git+HEAD go1.10.3 linux amd64`
- Installation method: `go get -v github.com/gopasspw/gopass`

**Comment by dominikschulz** [comment]
Well ... that depends on the expected behaviour. In my tests gopass performed exactly as I expected it, i.e. it initialized a new password store at `$HOME/foobar`. What it didn't do (and what I didn't expect it to) was to update the config.

The primary use-case for `gopass init` is to initialize a new password store in a non-standard location which can then be used as a mount or remote.

We could add an option to make `gopass init` update the config as well, but so far this wasn't necessary.

**Comment by frntn** [comment]
Hmmm... I don't get it.

I exec the `gopass init` command which successfully complete,
Then while trying to exec `gopass` it tells me that gopass hasn't been initialized.

That doesn't look like an expected behavior for me.
Moreover when I can point out why it _thinks_ gopass has not been initialized : the `config.yml` file doesn't refer to the store I had passed to the init commande using `--path`

Why would one think that `gopass init --path /foo/bar` should not endup setting the `config.yml` with the `/foo/bar` path ?

**Comment by dominikschulz** [comment]
This must have been fixed in the meantime. I can't reproduce with the current head anymore. Please re-open if this still affects you.

**Comment by frntn** [comment]
Just tried with a fresh ubuntu install
```
[~] 
>_ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

[~] 
>_ ls -ld $HOME/foobar $HOME/.password-store
ls: cannot access '/home/mfronton/foobar': No such file or directory
ls: cannot access '/home/mfronton/.password-store': No such file or directory
```

With the latest gopass 1.9.2
```
[~] 
>_ gopass --version
gopass 1.9.2+e2d1549f452a0df1fc52e42e7d0f654334d7144e (e2d1549f452a0df1fc52e42e7d0f654334d7144e) go1.14.2 linux amd64
```

I still reproduce : gopass init on a custom path performs without error
```
[~] 
>_ gopass init --path $HOME/foobar
[init] Initializing a new password store ...
Please select a private key for encrypting secrets:
[0] gpg - 0xD385289FA809234F - Matthieu Fronton <m@tthieu.fr>
Please enter the number of a key (0-0, [q]uit) [0]: 
[init] Initializing git repository (gitcli) ...
Use Matthieu Fronton (m@tthieu.fr) for password store git config? [Y/n/q]: 
[init] git initialized at /home/mfronton/foobar
[init] git configured at /home/mfronton/foobar
[init] Git initialized
[init] Password store /home/mfronton/foobar initialized for:
[init]   0xD385289FA809234F - Matthieu Fronton <m@tthieu.fr>
```

But gopass then warns the repo is not initialized
```
[~] 
>_ gopass
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: q
Error: failed to list store: lstat /home/mfronton/.password-store: no such file or directory
```

We can see the custom path has been initialized on the filesystem
```
[~] 
>_ ls -ld $HOME/foobar $HOME/.password-store
ls: cannot access '/home/mfronton/.password-store': No such file or directory
drwx------ 4 mfronton mfronton 4096 août   1 23:50 /home/mfronton/foobar

[~] 
>_ ll $HOME/foobar/
total 24
drwx------  4 mfronton mfronton 4096 août   1 23:50 ./
drwxr-xr-x 27 mfronton mfronton 4096 août   1 23:50 ../
drwx------  8 mfronton mfronton 4096 août   1 23:50 .git/
-rw-------  1 mfronton mfronton   15 août   1 23:50 .gitattributes
-rw-------  1 mfronton mfronton   19 août   1 23:50 .gpg-id
drwx------  2 mfronton mfronton 4096 août   1 23:50 .public-keys/
```

But the config file refers to the same old .password-store folder
```
[~] 
>_ cat .config/gopass/config.yml 
root:
  askformore: false
  autoclip: false
  autoprint: false
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  exportkeys: true
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: true
  path: gpgcli-gitcli-fs+file:///home/mfronton/.password-store
  recipient_hash:
    .gpg-id: 3078443338353238394641383039323334460aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
  safecontent: false
  usesymbols: false
mounts: {}
```

Change the path in the config files seems enough to fix the issue

**Comment by dominikschulz** [comment]
I guess it might be fixed with the upcoming 1.9.3 but not yet with 1.9.2.

I'll try to reproduce both and close the bug again if it's working with 1.9.3.

**Comment by dominikschulz** [comment]
With the current master this seems to be fixed:

```
$ gopass init --path /tmp/foo
[init] Initializing a new password store ...
[...]
[init] Password store /tmp/foo initialized for:
[...]
$ cat .config/gopass/config.yml
autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: true
nocolor: false
nopager: false
notifications: true
parsing: true
path: /tmp/foo
safecontent: false
mounts: {}
$ gopass ls
gopass
```
